'use strict';
const {roles,skills}=window.GAME_DATA;
const {issues,drafts}=window.REVIEW_DATA;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const skillMap=new Map(skills.map(s=>[s.name,s]));
const redesignedArt={"mentor":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留圆眼镜、长胡须与 A 徽章，减少脸部及胡须的密集排线。","union":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留工装背带裤、卷袖衬衫与举拳动作；英文条幅 SOLIDARITY、讲台 UNION。","assassin":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留礼帽、小胡须、持枪动作及沉着表情。","worker":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。将符号化形象重绘为有清晰五官的工农，保留草帽、工装与农叉。","cultist":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留软尖帽、长袍、手杖与举指动作，以夸谈神态表现神棍。","spy":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留低帽檐与高领大衣，加入警觉的侧视眼神。","scab":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留安全帽与眼罩，补全工装及人物面部。","police":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留军帽、制服、大胡须与佩刀，调整成人比例和傲慢神态。","capitalist":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。全套画风主参考，保留高礼帽、单片眼镜、卷胡须及简洁排线。","church":"以资佬为主参考统一重绘，采用复古钢笔轮廓与少量排线。保留虚构贪婪教权人物的负面讽刺形象、赎罪券与钱袋，减少细密纹饰；标题 INDULGENCE。"};
let filter='all',currentRole=null,detailMode='original',toastTimer;
let favorites=new Set();
try { const saved=JSON.parse(localStorage.getItem('1886-favorites')||'[]'); if(Array.isArray(saved)) favorites=new Set(saved.filter(id=>roles.some(r=>r.id===id))); } catch {}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);try{localStorage.setItem('1886-favorites',JSON.stringify([...favorites]));}catch{} renderRoster();if(currentRole?.id===id)renderDetail();notify(favorites.has(id)?'已收藏此角色':'已取消收藏');}
function changeView(view){if(!['roster','arena','review','rules'].includes(view))view='roster';$$('.view').forEach(el=>{el.hidden=el.id!=='view-'+view;el.classList.toggle('active',!el.hidden);});$$('.nav-item').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);el.setAttribute('aria-current',el.dataset.view===view?'page':'false');});document.title='1886 — '+({roster:'角色图鉴',arena:'对局练习',review:'设计分析',rules:'规则手册'}[view]);}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){location.hash=nav.dataset.view;changeView(nav.dataset.view);window.scrollTo({top:0,behavior:'instant'});}});
window.addEventListener('hashchange',()=>{changeView(location.hash.slice(1));window.scrollTo({top:0,behavior:'instant'});});

function renderRoster(){const q=$('#role-search').value.trim().toLowerCase();const shown=roles.filter(r=>(filter==='all'||filter==='favorites'&&favorites.has(r.id)||filter==='people'&&r.faction==='群众'||r.group===filter)&&(!q||[r.name,r.faction,r.position,...r.signature,...r.common,...r.shared,...r.joint].join(' ').toLowerCase().includes(q)));$('#roster-grid').innerHTML=shown.map(r=>{const keySkills=r.signature.length?r.signature:r.group==='hidden'?['潜伏','继任']:r.common;return `<article class="role-card ${r.group}" data-faction="${r.group}"><button class="card-open" data-role="${r.id}" aria-label="查看${r.name}的角色与技能"><div class="card-head"><span>${esc(r.faction)}${r.group==='hidden'?' · 潜伏':''}</span><small>No. ${String(roles.indexOf(r)+1).padStart(2,'0')}</small></div><div class="card-art"><img src="${r.art}" alt="${esc(r.name)}${redesignedArt[r.id]?'新版插画':'原稿插画'}" loading="lazy"><span class="card-art-label">${r.group==='hidden'?'身份隐藏':r.count>1?'三人角色':'身份公开建议'}</span></div><div class="card-body"><div class="card-title"><h3>${esc(r.name)}</h3><span class="health" aria-label="生命 4">◆◆◆◆</span></div><div class="card-position">${esc(r.position)}</div><div class="card-skills">${keySkills.map(s=>`<span class="skill-chip">${esc(s)}</span>`).join('')}</div><div class="card-bottom"><span>手牌上限 ${r.limit}</span><span>查看详情 ↗</span></div></div></button><button class="card-favorite ${favorites.has(r.id)?'saved':''}" data-favorite="${r.id}" aria-label="${favorites.has(r.id)?'取消收藏':'收藏'}${esc(r.name)}" aria-pressed="${favorites.has(r.id)}">${favorites.has(r.id)?'★':'☆'}</button></article>`;}).join('');$('#roster-count').textContent=`显示 ${shown.length} / ${roles.length} 种角色` ;$('#roster-empty').hidden=shown.length>0;}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderRoster();}));
$('#role-search').addEventListener('input',renderRoster);
document.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){toggleFavorite(fav.dataset.favorite);return;}const card=e.target.closest('[data-role]');if(card)openRole(card.dataset.role);});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('#role-dialog').open&&!$('#view-roster').hidden){e.preventDefault();$('#role-search').focus();}});
function openRole(id){currentRole=roles.find(r=>r.id===id);detailMode='original';renderDetail();$('#role-dialog').showModal();document.body.style.overflow='hidden';}
$('#role-dialog').addEventListener('close',()=>{document.body.style.overflow='';currentRole=null;});
$('.dialog-close').addEventListener('click',()=>$('#role-dialog').close());
$('#role-dialog').addEventListener('click',e=>{if(e.target===$('#role-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function skillMarkup(name,tag='角色技'){const s=skillMap.get(name);if(!s)return '';return `<div class="detail-skill"><h4>${esc(name)}<span>${tag}</span></h4><p>${esc(detailMode==='draft'?drafts[name]||s.original:s.original)}</p><div class="source">${detailMode==='draft'?'试改建议 · 原文参考：':'来源：'}${esc(s.source)}</div></div>`;}
function renderDetail(){const r=currentRole;if(!r)return;$('#role-detail').innerHTML=`<div class="detail-layout"><aside class="detail-profile" data-faction="${r.group}"><div class="eyebrow">${esc(r.faction)} / ${r.group==='hidden'?'潜伏继任':esc(r.position)}</div><h2 id="detail-title">${esc(r.name)}</h2><div class="detail-portrait"><img src="${r.art}" alt="${esc(r.name)}${redesignedArt[r.id]?'新版插画':'原稿插画'}"></div><p class="tagline">${esc(r.tagline)}</p><div class="detail-stat"><span>生命上限</span><strong>◆ ◆ ◆ ◆</strong></div><div class="detail-stat"><span>手牌上限</span><strong>${r.limit} 张</strong></div><div class="detail-stat"><span>完整局席位</span><strong>${r.count} 人</strong></div><button class="secondary" data-favorite="${r.id}">${favorites.has(r.id)?'★ 已收藏':'☆ 收藏角色'}</button></aside><div class="detail-content"><div class="detail-tabs"><button data-detail-mode="original" class="${detailMode==='original'?'active':''}">原始设定</button><button data-detail-mode="draft" class="${detailMode==='draft'?'active':''}">试改建议</button></div><p class="detail-desc">${esc(r.tags)} · ${esc(r.position)}</p>${detailMode==='draft'?'<div class="detail-warning">这些是供你审阅的试改文本，尚未经过对局验证；原始设定可随时切回查看。</div>':''}${r.group==='hidden'?'<div class="detail-warning">潜伏前技能存在歧义：合并单元格覆盖了该角色，但技能正文写的是“工农及反抗”。下方暂按表格区域展示，适用对象需要确认。</div>':''}<h3>角色能力</h3>${r.signature.map(s=>skillMarkup(s)).join('')}${r.common.map(s=>skillMarkup(s,r.group==='hidden'?'适用待确认':'群众技')).join('')}${r.group==='hidden'?`<div class="detail-skill"><h4>潜伏继任<span>身份机制</span></h4><p>${esc(r.victory)}</p><div class="source">${esc(r.victorySource)}</div></div>`:''}<details><summary>阵营通用技与联合技 · ${r.shared.length+r.joint.length} 项</summary>${r.shared.map(s=>skillMarkup(s,'通用技')).join('')}${r.joint.map(s=>skillMarkup(s,'联合技')).join('')}</details><h3>胜利条件 · 原文</h3><div class="detail-victory">${esc(r.victory)}</div><div class="source">${esc(r.victorySource)}</div><div class="detail-review">${esc(r.review)}</div><div class="source">卡牌信息：${esc(r.source)}；生命：角色与技能表!C56。${esc(redesignedArt[r.id]||'插画对应角色按画面推定，原图未标注角色名称。')}</div></div></div>`;}
$('#role-detail').addEventListener('click',e=>{const b=e.target.closest('[data-detail-mode]');if(b){detailMode=b.dataset.detailMode;renderDetail();$(`[data-detail-mode="${detailMode}"]`).focus();}});

function renderIssues(kind='all'){$('#issues-list').innerHTML=issues.map((issue,i)=>({issue,i})).filter(x=>kind==='all'||x.issue.kind===kind).map(({issue:i,i:n})=>`<article class="issue"><div class="issue-num">${String(n+1).padStart(2,'0')}</div><div><span class="issue-badge ${i.kind==='优先实测'?'priority':''}">${esc(i.kind)}</span><h3>${esc(i.title)}</h3><div class="who">${esc(i.who)}</div><p>${esc(i.detail)}</p><div class="source">依据：${esc(i.source)}</div></div><div class="suggestion"><b>建议怎么处理</b><p>${esc(i.suggestion)}</p></div></article>`).join('');}
$$('[data-issue-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-issue-filter]').forEach(x=>x.classList.toggle('active',x===b));renderIssues(b.dataset.issueFilter);}));
function renderSkillIndex(){const q=$('#skill-search').value.trim();const found=skills.filter(s=>(s.name+s.original).includes(q));$('#skill-index').innerHTML=found.length?found.map(s=>`<details class="skill-entry"><summary><span>${esc(s.name)}</span><small>${String(s.id).padStart(2,'0')}</small></summary><p>${esc(s.original)}</p><div class="source">来源：${esc(s.source)}</div></details>`).join(''):'<div class="empty">没有找到对应技能。</div>';}
$('#skill-search').addEventListener('input',renderSkillIndex);
function updateLab(){const a=Number($('#attack-range').value),d=Number($('#defense-range').value);$('#attack-output').value=a;$('#defense-output').value=d;$('#number-result').classList.toggle('success',d>=a);$('#number-result').textContent=d>=a?`防 ${d} ≥ 斗 ${a} · 成功抵挡`:`防 ${d} < 斗 ${a} · 受到 1 点伤害`;}
$('#attack-range').addEventListener('input',updateLab);$('#defense-range').addEventListener('input',updateLab);

// Deliberately bounded practice rules. No character skills or identity victory are implied.
let game;
const suits=['♠','♥','♣','♦'];
const typeOf=rank=>[3,5,7,9].includes(rank)?'斗':[2,4,6,8,10].includes(rank)?'防':rank===1?'救援':rank===13?'决斗':'资源';
const face=c=>({1:'A',11:'J',12:'Q',13:'K'}[c.rank]||c.rank);
const cardText=c=>c?`${c.suit}${face(c)} ${c.type}`:'无斗（0）';
const red=c=>c.suit==='♥'||c.suit==='♦';
function shuffle(cards){for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}return cards;}
function addLog(msg){game.log.unshift({turn:game.turn,msg});if(game.log.length>80)game.log.pop();}
function drawFor(who,n){let drawn=0;for(let i=0;i<n;i++){if(!game.deck.length&&game.discard.length){game.deck=shuffle(game.discard.splice(0));addLog('弃牌堆重新洗入牌堆。');}if(!game.deck.length)break;game[who].hand.push(game.deck.pop());drawn++;}return drawn;}
function consume(who,id){const index=game[who].hand.findIndex(c=>c.id===id);if(index<0)return null;const [card]=game[who].hand.splice(index,1);game.discard.push(card);return card;}
function resetGame(){const cards=[];let id=0;for(let deck=0;deck<2;deck++)for(const suit of suits)for(let rank=1;rank<=13;rank++)cards.push({id:id++,rank,suit,type:typeOf(rank)});const pick=(rank,suit)=>cards.splice(cards.findIndex(c=>c.rank===rank&&c.suit===suit),1)[0];const playerHand=[pick(7,'♠'),pick(9,'♥'),pick(6,'♣'),pick(1,'♥'),pick(13,'♦'),pick(12,'♠')];const enemyHand=[pick(5,'♣'),pick(9,'♣'),pick(8,'♦'),pick(10,'♠'),pick(1,'♣'),pick(13,'♠')];game={turn:1,phase:'play',deck:shuffle(cards),discard:[],player:{hp:3,hand:playerHand},enemy:{hp:3,hand:enemyHand},selected:new Set(),attackUsed:false,log:[],lastCards:[],status:'轮到你出牌。选一张斗攻击，或用 A 回复体力。',pending:null};addLog('教学预设已就绪。你的对手是军警，双方角色技能在本练习中关闭。');renderGame();}
function validCard(c){if(game.phase==='play')return c.type==='斗'&&!game.attackUsed||c.type==='救援'&&game.player.hp<4||c.type==='决斗';if(game.phase==='response')return c.type==='防'&&c.rank>=game.pending.rank;if(game.phase==='duel')return c.type==='斗';return game.phase==='discard';}
function hurt(who){game[who].hp=Math.max(0,game[who].hp-1);if(!game[who].hp){game.phase='over';game.status=who==='enemy'?'你赢得了本次练习。正式阵营胜负需在完整规则中结算。':'你的体力降为 0，本次练习结束。可以重新发牌再试一次。';addLog(who==='enemy'?'对手体力降为 0，练习结束。':'你的体力降为 0，练习结束。');game.selected.clear();return true;}return false;}
function selectedCard(){return game.player.hand.find(c=>game.selected.has(c.id));}
function selectCard(id){const card=game.player.hand.find(c=>c.id===id);if(!card||!validCard(card))return;if(game.phase!=='discard')game.selected.clear();else if(game.selected.has(id)){game.selected.delete(id);renderGame();return;}game.selected.add(id);renderGame();}
function playSelected(){if(game.phase==='discard'){const excess=game.player.hand.length-5;if(game.selected.size!==excess)return;[...game.selected].forEach(id=>consume('player',id));addLog(`你弃置 ${excess} 张手牌，保留 5 张。`);game.selected.clear();enemyTurn();return;}const card=selectedCard();if(!card||!validCard(card))return;game.selected.clear();if(game.phase==='response'){consume('player',card.id);game.lastCards=[game.pending,card];addLog(`你打出${cardText(card)}，抵挡${cardText(game.pending)}。`);game.status=`防 ${card.rank} 成功抵挡斗 ${game.pending.rank}。`;game.pending=null;startPlayerTurn();return;}if(game.phase==='duel'){resolveDuel(card);return;}consume('player',card.id);game.lastCards=[card];if(card.type==='救援'){game.player.hp=Math.min(4,game.player.hp+1);addLog(`你使用${cardText(card)}，回复 1 点体力。`);game.status='救援生效。你的体力回复 1 点。';}else if(card.type==='斗'){game.attackUsed=true;const defense=game.enemy.hand.filter(c=>c.type==='防'&&c.rank>=card.rank).sort((a,b)=>a.rank-b.rank)[0];if(defense){consume('enemy',defense.id);game.lastCards.push(defense);addLog(`你打出${cardText(card)}，对手以${cardText(defense)}抵挡。`);game.status=`斗 ${card.rank} 被防 ${defense.rank} 抵挡。本回合普通斗次数已用完。`;}else{addLog(`你打出${cardText(card)}，对手没有有效防，受到 1 点伤害。`);game.status='对手没有足够点数的防，受到 1 点伤害。';hurt('enemy');}}else if(card.type==='决斗'){game.phase='duel';game.status='决斗：选择一张斗，同时与对手比大小。同点数均无伤。';addLog(`你使用${cardText(card)}，发起决斗。`);if(!game.player.hand.some(c=>c.type==='斗')){resolveDuel(null);return;}}renderGame();}
function resolveDuel(playerCard){const opponent=game.enemy.hand.filter(c=>c.type==='斗').sort((a,b)=>b.rank-a.rank)[0];if(playerCard)consume('player',playerCard.id);if(opponent)consume('enemy',opponent.id);game.lastCards=[playerCard,opponent].filter(Boolean);const p=playerCard?.rank||0,e=opponent?.rank||0;game.phase='play';game.selected.clear();if(p===e){game.status=`决斗点数 ${p} : ${e}，双方均不受伤。`;addLog(`决斗：你 ${p}，对手 ${e}。平局。`);}else{const loser=p<e?'player':'enemy';game.status=`决斗点数 ${p} : ${e}，${loser==='player'?'你':'对手'}受到 1 点伤害。`;addLog(game.status);hurt(loser);}renderGame();}
function endTurn(){if(game.phase==='response'){addLog(`你未打出有效防，受到${cardText(game.pending)}的 1 点伤害。`);game.status='你选择承受 1 点伤害。';game.pending=null;if(hurt('player')){renderGame();return;}startPlayerTurn();return;}if(game.phase!=='play')return;game.selected.clear();if(game.player.hand.length>5){game.phase='discard';game.status=`弃牌阶段：请选择 ${game.player.hand.length-5} 张手牌弃置。`;renderGame();return;}enemyTurn();}
function enemyTurn(){game.phase='enemy';game.selected.clear();const n=drawFor('enemy',2);addLog(`对手摸了 ${n} 张牌。`);const aid=game.enemy.hand.find(c=>c.type==='救援');if(aid&&game.enemy.hp<4){consume('enemy',aid.id);game.enemy.hp++;addLog('对手使用救援，回复 1 点体力。');}const attack=game.enemy.hand.filter(c=>c.type==='斗').sort((a,b)=>a.rank-b.rank)[0];if(attack){consume('enemy',attack.id);game.pending=attack;game.lastCards=[attack];game.phase='response';game.status=`军警使用斗 ${attack.rank}。请打出点数不小于 ${attack.rank} 的防，或承受伤害。`;addLog(`对手使用${cardText(attack)}，等待你的响应。`);renderGame();}else{game.status='对手没有斗，本轮未发起攻击。';addLog(game.status);startPlayerTurn();}}
function startPlayerTurn(){if(game.phase==='over')return;const excess=Math.max(0,game.enemy.hand.length-5);if(excess){game.enemy.hand.sort((a,b)=>(a.type==='资源'?0:1)-(b.type==='资源'?0:1));for(let i=0;i<excess;i++)consume('enemy',game.enemy.hand[0].id);addLog(`对手弃置 ${excess} 张牌，保留 5 张。`);}game.turn++;game.phase='play';game.attackUsed=false;game.selected.clear();const n=drawFor('player',2);addLog(`你的第 ${game.turn} 回合开始，摸了 ${n} 张牌。`);game.status+=` 你的回合开始，已摸 ${n} 张。`;renderGame();}
function personMarkup(who){const p=game[who],isPlayer=who==='player',r=roles.find(role=>role.id===(isPlayer?'mentor':'police'));return `<div class="combat-portrait"><img src="${esc(r.art)}" alt="${esc(r.name)}"></div><div><h3>${isPlayer?'导师':'军警'}<small>${isPlayer?'你 · 反抗':'练习对手 · 权威'}</small></h3><div class="hp" aria-label="体力 ${p.hp}，上限 4">${'◆'.repeat(p.hp)}<span class="lost">${'◆'.repeat(4-p.hp)}</span><small>${p.hp} / 4</small></div><div class="combat-meta">手牌 ${p.hand.length} 张 · 角色技能关闭</div></div>`;}
function renderGame(){$('#round-label').textContent=`练习回合 ${String(game.turn).padStart(2,'0')}`;$('#deck-label').textContent=`牌堆 ${game.deck.length} · 弃牌 ${game.discard.length}`;$('#enemy-panel').innerHTML=personMarkup('enemy');$('#player-panel').innerHTML=personMarkup('player');$('#battle-status').textContent=game.status;$('#battle-cards').innerHTML=game.lastCards.map(c=>`<div class="played-card ${red(c)?'red':''}">${c.suit}${face(c)}<small>${c.type==='救援'?'援':c.type==='决斗'?'决':c.type}</small></div>`).join('');$('#hand-count').textContent=`${game.player.hand.length} / 5`;$('#hand-help').textContent=game.phase==='discard'?`已选 ${game.selected.size} 张 · 需弃 ${game.player.hand.length-5} 张`:game.phase==='response'?'选择一张有效防':game.phase==='duel'?'选择一张斗参与决斗':game.phase==='over'?'练习结束':game.attackUsed?'本回合普通斗次数已用完':'本回合可使用 1 张斗';$('#hand').innerHTML=game.player.hand.map(c=>`<button class="playing-card ${red(c)?'red':''} ${game.selected.has(c.id)?'selected':''}" data-card="${c.id}" aria-label="${cardText(c)}" aria-pressed="${game.selected.has(c.id)}" ${validCard(c)?'':'disabled'}><span class="card-corner">${face(c)}<small>${c.suit}</small></span><span class="card-glyph">${c.type==='救援'?'援':c.type==='决斗'?'决':c.type==='资源'?'筹':c.type}</span><span class="play-type">${c.type==='资源'?'技能资源':c.type==='救援'?'回复体力':c.type==='决斗'?'点数对决':c.type==='防'?'响应牌':'攻击牌'}</span></button>`).join('');const c=selectedCard(),play=$('#play-card');play.disabled=game.phase==='discard'?game.selected.size!==game.player.hand.length-5:!c||!validCard(c);play.textContent=game.phase==='discard'?'确认弃牌':game.phase==='response'?'打出防':game.phase==='duel'?'确认决斗牌':c?`使用${c.type}`:'选择手牌';$('#cancel-card').disabled=!game.selected.size;$('#end-turn').textContent=game.phase==='response'?'承受伤害':game.phase==='over'?'练习结束':'结束回合 →';$('#end-turn').disabled=!['play','response'].includes(game.phase);$('#game-log').innerHTML=game.log.map(l=>`<div><small>${String(l.turn).padStart(2,'0')}</small>${esc(l.msg)}</div>`).join('');}
$('#hand').addEventListener('click',e=>{const c=e.target.closest('[data-card]');if(c&&!c.disabled)selectCard(Number(c.dataset.card));});
$('#play-card').addEventListener('click',playSelected);$('#end-turn').addEventListener('click',endTurn);$('#reset-game').addEventListener('click',()=>{resetGame();notify('已重新发牌，回到教学开局。');});$('#cancel-card').addEventListener('click',()=>{game.selected.clear();renderGame();});
function renderFeaturedArt(){$$('[data-role-art]').forEach(img=>{const r=roles.find(role=>role.id===img.dataset.roleArt);if(r)img.src=r.art;});}
renderFeaturedArt();renderRoster();renderIssues();renderSkillIndex();updateLab();resetGame();changeView(location.hash.slice(1)||'roster');
