'use strict';
// A deterministic teaching storyboard, not a competitive rules engine.
// Replay reconstructs snapshots from the beginning, so seeking never accumulates effects.
const ids=['mentor','union','assassin','worker1','worker2','worker3','cultist','spy','scab','police','capitalist','church'];
const seatNames=['导师','工会','刺客','工农甲','工农乙','工农丙','神棍','密探','工贼','军警','资佬','教会'];
const locations=[[1,2],[1,3],[1,4],[1,5],[2,6],[3,6],[4,5],[4,4],[4,3],[4,2],[3,1],[2,1]];
const roleFor=id=>GAME_DATA.roles.find(r=>r.id===(id.startsWith('worker')?'worker':id));
const events=[];
function add(chapter,title,actor,targets,cards,result,voice,skills=[],effects=[],note=''){events.push({chapter,title,actor,targets,cards,result,voice,skills,effects,note,duration:Math.max(9,voice.length/4.4+1.2)});}
const common='教学脚本：关键手牌预设，动画展示结算逻辑；并非完整牌堆或自动对战。';
add('序章 / 游戏总览','十二个席位，三方角力','',[],[],'十种角色 · 工农三席 · 其余各一席','这是一场安那其一八八六的十二人教学牌局。十种角色全部入场，工农有三人。我们从开局开始，依次看出牌、响应、角色技能与阵营协作。');
add('序章 / 阵营与胜利','谁是同伴，谁在等待机会？','mentor',['worker1','worker2','worker3'],[],'反抗与工农：击败权威并保住工农；权威：击败反抗','锈红是反抗，赭黄是群众，灰蓝是权威。反抗与真实工农的胜利，需要权威全部出局，并保住至少一名真实工农。权威需要反抗全部出局。潜伏者原稿则以成为对应权威角色为胜利条件，判定时点待明确。教学公开潜伏身份，实战需要隐藏。');
add('开局 / 发牌','全员四点生命，预设四张手牌','mentor',ids,['4|起始手牌'],'生命上限 4 · 资佬手牌上限 10，其他人 5','演示开局每人四点生命、四张手牌。资佬的贪婪让手牌上限达到十，其他角色为五。画面显示生命和手牌数量，关键牌经过预设，便于讲解。',['贪婪'],[],common);
add('第 1 轮 · 导师回合 / 摸牌','回合从摸两张牌开始','mentor',[],['+2|摸牌'],'摸牌 → 出牌 → 弃牌 → 下一席','每个普通回合先摸两张牌。导师现在得到两张手牌，随后可以使用基础牌或技能，最后把手牌弃到上限。演示按席位顺序推进。',[],[['mentor',0,2]]);
add('第 1 轮 · 导师回合 / 基础牌','斗七遇上防八','mentor',['police'],['♠7|斗','♣8|防'],'8 ≥ 7，军警成功抵挡','导师对军警打出斗七，军警用防八回应。防的点数不小于斗，才能挡住。这次双方各用一张牌，没有人失去生命。普通斗每回合通常只能一次。',['斗','防'],[['mentor',0,-1],['police',0,-1]]);
add('第 1 轮 · 导师回合 / 协作','互助：把合适的牌交给同伴','mentor',['worker1'],['↔|换牌'],'两人交换各一张牌，手牌数量不变','导师与工农甲发动互助，各交换一张手牌。交换不会改变数量，但会改变可用的行动。如果对方没有手牌，则可以直接赠送一张。',['互助']);
add('第 1 轮 · 工会回合','合作社让七名同伴补牌','union',['mentor','assassin','worker1','worker2','worker3'],['♥J|合作社'],'反抗与群众共九席各补 1 张','工会摸两张后，使用红桃J发动合作社。所有群众和反抗角色各获得一张牌。这里包含三个初始群众身份的潜伏者，展示群体收益。',['合作社'],[['union',0,2],['union',0,-1],...ids.slice(0,9).map(id=>[id,0,1])]);
// Exact public side count is nine: three rebels + three workers + three infiltrators.
events.at(-1).title='合作社：反抗与群众共同补牌';
add('第 1 轮 · 刺客回合','第一次进攻被挡住','assassin',['capitalist'],['♠7|斗','♦8|防'],'资佬打出防八 → 开启刺杀追击窗口','刺客摸两张牌，先对资佬使用斗七。资佬以防八抵挡。对多数角色来说，普通斗已经用完，但刺客拥有特殊的追击条件。',['斗','防'],[['assassin',0,2],['assassin',0,-1],['capitalist',0,-1]]);
add('第 1 轮 · 刺客回合 / 角色技','刺杀：第二次出手','assassin',['capitalist'],['♥9|追击斗'],'资佬没有足够的防，失去 1 点生命','第一张斗被防住后，刺客发动刺杀，再出斗九。资佬这次无法抵挡，生命从四降到三。注意，这是角色技能提供的额外进攻机会。',['刺杀'],[['assassin',0,-1],['capitalist',-1,0]]);
add('第 1 轮 · 工农甲回合','爆料揭露：把信息公开','worker1',['church'],['Q|爆料揭露'],'教会手牌公开；数量不改变','工农甲摸两张，使用Q发动爆料揭露，公开教会手牌。看到对手有哪些防、决斗和救援牌，能帮助团队选择下一个目标。',['爆料揭露'],[['worker1',0,1]],'公开手牌仅展示信息效果；本片不展示一副真实随机牌堆。');
add('第 1 轮 · 工农乙回合','躺平隐匿：这一回合不出牌','worker2',[],['—|不出牌'],'获得躺平标记：规避部分索取','工农乙摸两张，但选择不出牌，发动躺平隐匿。之后的征税、赎罪券和剥削不会影响他。演示约定保护持续到本人下个回合，正式持续时间仍需确定。',['躺平隐匿'],[['worker2',0,2]],'演示约定：保护到本人下个回合；摸牌后依然需要遵守弃牌上限。');
add('第 1 轮 · 工农丙回合','保留一张高点数防','worker3',[],['10|留作响应'],'摸牌后整理手牌，准备为同伴掩护','工农丙摸两张，保留高点数防。出牌阶段没有行动，不意味着这名角色不重要。在其他人的回合里，他仍可能通过掩护，为同伴打出防。',[],[['worker3',0,2]]);
add('第 1 轮 · 神棍回合','潜伏者也使用基础牌','cultist',['scab'],['K|决斗','7|神棍','5|工贼'],'7 > 5，工贼失去 1 点生命','神棍摸两张，对工贼打出决斗。演示采用双方各出一张斗比点数，七大于五，工贼失去一点生命。潜伏身份不妨碍使用普通基础牌。',['决斗'],[['cultist',0,0],['scab',-1,-1]],'决斗演示约定：各出一张斗，低者失血，同点无伤；不是轮流出斗版本。');
add('第 1 轮 · 密探回合','密探：隐藏的继任方向','spy',[],['+2|摸牌'],'军警出局后，密探可能继任军警','密探摸两张，暂时保存实力。他表面属于群众，真正的特殊机制是军警出局后继任。继任前群众技能的适用范围有歧义，因此本演示只展示他的基础行动。',[],[['spy',0,2]],'潜伏机制依原稿；继任前不擅自授予有争议的群众技能。');
add('第 1 轮 · 工贼回合','救援：把生命补回来','scab',[],['A|救援'],'工贼生命 3 → 4','工贼先摸两张，再使用A救援自己，恢复一点生命，回到上限四。救援是每个角色都能理解和使用的基础行动。完整多人救援窗口仍需要细化。',['救援'],[['scab',1,1]]);
add('第 1 轮 · 军警回合 / 摸牌阶段','征税：资源向权威集中','police',['mentor','union','assassin','worker1'],['4|抽取保留'],'四席各失去 1 张，军警获得 4 张','军警发动征税。这里选取导师、工会、刺客和工农甲，各抽一张并保留四张。工农乙有躺平保护，教会则因神权免疫。原稿允许更大范围，剩余牌处理仍需明确。',['征税','神权','躺平隐匿'],[['police',0,4],...['mentor','union','assassin','worker1'].map(id=>[id,0,-1])],'简化展示四名有效目标；不把此目标数上限当成正式规则。');
add('第 1 轮 · 军警回合 / 信息','搜查：公开刺客的手牌','police',['assassin'],['J|搜查'],'刺客手牌信息公开','军警使用J发动搜查，公开刺客手牌。与直接造成伤害不同，信息技能让下一次进攻更有把握。公开不会让目标额外丢牌。',['搜查'],[['police',0,-1]]);
add('第 1 轮 · 军警回合 / 进攻','掩护：工农丙替导师打出防','police',['mentor','worker3'],['7|军警斗','10|掩护防'],'工农丙消耗防十，导师不受伤','军警用斗七攻击导师。工农丙发动掩护，替导师打出防十，成功挡下。受到保护的是导师，消耗手牌的却是工农丙，这就是团队响应。',['掩护','斗','防'],[['police',0,-1],['worker3',0,-1]]);
add('第 1 轮 · 资佬回合 / 取牌','巧取豪夺引出忍辱复仇','capitalist',['worker1'],['J|巧取豪夺','斗|复仇补牌'],'工农甲失去 1 张，再获得 1 张斗','资佬摸两张，用J发动巧取豪夺，拿走工农甲一张牌。工农甲因此触发忍辱复仇，获得一张斗。防守方并非只能承受，也可能得到反击资源。',['巧取豪夺','忍辱复仇'],[['capitalist',0,2]],'演示约定：忍辱获得的斗来自预设补牌，不消耗其他玩家手牌。');
add('第 1 轮 · 资佬回合 / 信息','收买：同样可以打开信息','capitalist',['union'],['Q|收买'],'工会手牌公开','资佬使用Q发动收买，公开工会手牌。这个技能和搜查的目标类似，但需要的牌不同。技能设计既影响效果，也影响手中哪张牌更值得保留。',['收买'],[['capitalist',0,-1]]);
add('第 1 轮 · 资佬回合 / 阵营协作','内幕交易与手牌上限','capitalist',['church'],['↔|多张换牌'],'与教会各交换 2 张；资佬上限仍为 10','资佬与教会发动内幕交易，各交换两张牌，数量不变。贪婪让他保留更多资源。原稿中剥削和贪婪文字重复，因此这里展示重复问题，不凭空发明新效果。',['内幕交易','贪婪','剥削'],[],'剥削原文与贪婪重复，等待设计者给出独立效果。');
add('第 1 轮 · 教会回合 / 索取','赎罪券：交牌，或失去生命','church',['mentor','union','worker1','worker3'],['1|贡献牌'],'导师拒交失血，其余有效目标贡献手牌','教会发动赎罪券。导师拒绝交牌，失去一点生命；其他有效目标贡献一张牌。工农乙受躺平保护。群体技能会随人数放大，正是实测时要关注的问题。',['赎罪券'],[['mentor',-1,0],['church',0,9],...ids.filter(id=>!['church','mentor','worker2'].includes(id)).map(id=>[id,0,-1])]);
add('第 1 轮 · 受伤响应','遗志：受伤后把两张牌交给同伴','mentor',['union','worker1'],['+1|给工会','+1|给工农甲'],'导师获得 2 张并分给两名同伴','导师因刚才受到伤害，触发遗志，得到两张牌，再分别交给工会和工农甲。本示例选择全部转交；能否自留，原稿还需要写清楚。',['遗志'],[['union',0,1],['worker1',0,1]]);
add('第 1 轮 · 教会回合 / 离间','离间：让两名角色展开决斗','church',['assassin','worker3'],['J|离间','9|刺客','5|工农丙'],'工农丙失去 1 点生命','教会使用J发动离间，指定刺客和工农丙决斗。示例中刺客出九，工农丙出五，工农丙受到一点伤害。被迫消耗同伴资源，是这张技能牌的威胁。',['离间','决斗'],[['church',0,-1],['assassin',0,-1],['worker3',-1,-1]]);
add('第 1 轮 / 回合结束','弃到上限，第一轮结束','church',[],['5|普通上限','10|资佬上限'],'整理超限手牌；保留下一轮需要的牌','十二个席位完成第一轮。教学镜头集中呈现关键行动，各席结束时应弃到手牌上限。接下来进入第二轮，展示治疗、群体进攻和联合技能。',[],[],'手牌仅为教学计数；本步统一整理超限手牌，不代表真实回合可延后弃牌。');
add('第 2 轮 · 导师回合','鼓舞：一张红桃A，群体恢复','mentor',['mentor','worker3'],['♥A|鼓舞'],'受伤的导师和工农丙各恢复 1 点','导师摸两张，使用红桃A发动鼓舞。群众和反抗阵营中受伤的角色各恢复一点，未受伤者不超过生命上限。导师与工农丙恢复到四点。',['鼓舞'],[['mentor',1,1],['worker3',1,0]]);
add('第 2 轮 · 工会回合','救济：把人头牌转换为治疗','union',['capitalist'],['K|救济'],'资佬生命 3 → 4','工会摸两张，使用K发动救济，让资佬恢复一点生命。原文允许治疗任意角色，所以这里特意选择另一阵营，展示技能目标与阵营立场是两回事。',['救济'],[['union',0,1],['capitalist',1,0]]);
add('第 2 轮 · 刺客回合','炸弹：一次进攻，三个目标','assassin',['police','capitalist','church'],['♠Q|炸弹','7|虚拟斗'],'三名权威分别响应；本例均未抵挡','刺客使用黑桃Q发动炸弹，同时向三名权威产生虚拟斗。原稿没有给出点数，这里临时按七演示。三名目标各自响应，本例均失去一点生命。',['炸弹'],[['assassin',0,1],['police',-1,0],['capitalist',-1,0],['church',-1,0]],'未定稿约定：炸弹虚拟斗为 7 点；仅用于解释响应流程。');
add('第 2 轮 · 工农甲回合 / 联合','总罢工：凑齐三张K','worker1',['mentor','union'],['K|工农甲','K|导师','K|工会'],'下一轮，限制征税、剥削和赎罪券获牌','工农甲发起总罢工，导师和工会响应，合计三张K。权威下一轮无法通过征税、剥削和赎罪券获得手牌。联合技能的代价由三个人共同承担。',['总罢工'],[['worker1',0,1],['mentor',0,-1],['union',0,-1]],'总罢工只按原文限制获牌；是否连带禁止失血惩罚仍需明确。');
add('第 2 轮 · 工农乙回合 / 联合','民兵武装：两个人各出一张十','worker2',['worker3','cultist','spy','scab'],['10|工农乙','10|工农丙'],'所有初始群众角色各获得一张斗','工农乙结束躺平保护，摸牌后发起民兵武装，工农丙响应。两人各出一张十，让全部群众角色随机获得一张斗。这里用预设斗代表补牌结果。',['民兵武装'],[['worker2',0,1],['worker3',0,-1],...ids.slice(3,9).map(id=>[id,0,1])]);
add('第 2 轮 · 工农丙回合','用新获得的斗发起进攻','worker3',['police'],['9|斗'],'军警生命 3 → 2','工农丙摸牌后，用一张斗九攻击军警。军警没有足够点数的防，失去一点生命。上一回合联合技能提供的资源，现在转化成了实际进攻。',['斗'],[['worker3',0,1],['police',-1,0]]);
add('第 2 轮 · 神棍回合','神棍观察教会的生存状态','cultist',[],['+2|摸牌'],'潜伏目标：继任教会','神棍摸牌并等待。教会仍然存活，所以继任没有触发。潜伏者不是一开始就拥有权威技能；具体继任过程将在后面的独立规则分支中展示。',[],[['cultist',0,2]]);
add('第 2 轮 · 密探回合','密探选择保存手牌','spy',[],['+2|摸牌'],'潜伏目标：继任军警','密探摸牌后保存资源。军警虽然已经受伤，但仍有两点生命，密探不会提前转换身份。教学采用全知视角，因此观众能看到这个潜在变化。',[],[['spy',0,2]]);
add('第 2 轮 · 工贼回合','工贼补充基础资源','scab',[],['+2|摸牌'],'潜伏目标：继任资佬','工贼继续以群众身份摸牌，等待资佬出局后的继任窗口。三名潜伏者没有凭空增加的独立主动技能，他们的特殊之处在于身份变化。',[],[['scab',0,2]]);
add('第 2 轮 · 军警回合','征兵：交出斗，或受到伤害','police',['mentor','union','worker1','worker2','worker3','cultist','spy','scab','assassin','capitalist'],['斗|代价一','斗|代价二'],'导师没有交斗，失去 1 点；教会免疫','军警使用两张斗发动征兵。每名有效目标要交一张斗，否则失去一点生命。这里导师不交而失血，其他有效目标交斗。教会因神权免疫，不参与响应。',['征兵','神权'],[['police',0,0],['mentor',-1,0],...ids.filter(id=>!['police','mentor','church'].includes(id)).map(id=>[id,0,-1])],'演示中军警先摸两张再消耗两张斗；征兵不等于普通斗次数。');
add('第 2 轮 · 资佬回合 / 受击分支','转嫁矛盾：把斗转给另一人','capitalist',['worker1'],['J|转嫁矛盾','7|转移的斗'],'受击教学分支：工农甲承受此斗','来看独立的受击响应分支：假设资佬正遭到一张斗七，他使用J转嫁矛盾，把目标转给工农甲。工农甲仍可响应防，本例未抵挡而失去一点生命。',['转嫁矛盾'],[],'此镜头是响应机制插例，不改变连续牌局生命与手牌；正式使用时发生在被斗指定后。');
add('第 2 轮 · 教会回合 / 联合','三名权威共同发动大图沙','church',['police','capitalist','mentor','worker1','worker2','worker3'],['K|教会','K|军警','K|资佬'],'三张K：群众和反抗各出防，否则失血','教会、军警和资佬合计出三张K，发动原稿名为大图沙的联合技。群众与反抗各出一张防，否则失去一点生命。本例全体交防，演示群体响应顺序。',['大图沙'],[['church',0,1],['police',0,-1],['capitalist',0,1],...ids.slice(0,9).map(id=>[id,0,-1])],'本步先为资佬、教会补上回合摸牌；联合响应只要求交防，原文未要求比较斗点数。');
add('规则分支 / 不接续前局','三名潜伏者分别继任谁？','spy',['police','cultist','church','scab','capitalist'],['神棍→教会|继任','密探→军警|继任','工贼→资佬|继任'],'条件：对应权威出局，才触发继任','继任映射是神棍接替教会，密探接替军警，工贼接替资佬。这里是独立规则说明，没有让三名权威在前面的牌局中突然死亡。血量、手牌与胜利检查顺序仍需定稿。',[],[],'潜伏胜利原文写为成为对应角色后胜利；不把未经确认的“加入权威继续作战”当正式规则。');
add('总结 / 已展示全部 30 项技能','先有共识，再开始真正的对局','',[],[],'基础牌 · 角色技 · 通用技 · 联合技 · 潜伏机制','这场教学展示了两轮行动、四种基础牌，以及全部三十项技能的效果或待定问题。真正开局前，需要先统一争议规则。你可以拖动进度，逐步回看每次结算。');
add('体验 / 在线页面','轮到你来研究这张牌桌','',[],[],'zhishiren.github.io/ananqi-1886-card-game/','角色图鉴、规则原文和这份动态演示都保存在项目网站。欢迎带着具体回合与技能提出建议，让这套十二人阵营卡牌继续完善。');

const $=s=>document.querySelector(s);let index=0,playing=false,elapsed=0,last=0,rate=1;
const initial=()=>ids.map((id,i)=>({id,name:seatNames[i],role:roleFor(id),hp:4,hand:4,status:''}));
function snapshot(n){const state=initial();for(let k=0;k<=n;k++){for(const [id,hp,hand] of events[k].effects){const p=state.find(x=>x.id===id);p.hp=Math.max(0,Math.min(4,p.hp+hp));p.hand=Math.max(0,p.hand+hand);}if(events[k].title.startsWith('躺平'))state[4].status='躺平保护';if(events[k].skills.includes('民兵武装'))state[4].status='';if(events[k].title.startsWith('弃到'))state.forEach(p=>p.hand=Math.min(p.hand,p.role.limit));}return state;}
function render(n,t=0){index=Math.max(0,Math.min(events.length-1,n));const e=events[index],state=snapshot(index);$('#chapter').textContent=e.chapter;$('#title').textContent=e.title;$('#action').textContent=e.skills[0]||e.title;$('#result').textContent=e.result;$('#caption').textContent=e.voice;$('#explain-title').textContent=e.title;$('#explain').textContent=e.voice;$('#facts').innerHTML=e.skills.map(s=>`<span>${s}</span>`).join('');$('#convention').textContent=e.note||common;$('#skill-text').innerHTML=e.skills.map(name=>{const s=GAME_DATA.skills.find(x=>x.name===name);return s?`<p><b>${name}</b><br>${s.original}</p>`:'';}).join('');$('#cards').innerHTML=e.cards.map(c=>{const [v,l]=c.split('|');return `<div class="playing-card ${/[♥♦]/.test(v)?'red':''}">${v}<small>${l||''}</small></div>`;}).join('');$('#seats').innerHTML=state.map((p,i)=>`<article id="seat-${p.id}" class="seat ${p.role.group} ${p.id===e.actor?'active':''} ${e.targets.includes(p.id)?'target':''}" style="grid-row:${locations[i][0]};grid-column:${locations[i][1]}"><img src="${p.role.art}" alt="${p.name}"><div><small>席位 ${String(i+1).padStart(2,'0')}</small><h3>${p.name}</h3><div class="health">${'◆'.repeat(p.hp)}${'◇'.repeat(4-p.hp)}</div><div class="hand">手牌 ${p.hand}</div><small>${p.role.group==='hidden'?'群众 · 潜伏':p.role.faction}</small><div class="status">${p.status|| (p.id===e.actor?'正在行动':'')}</div></div></article>`).join('');$('#log').innerHTML=events.slice(Math.max(0,index-3),index+1).map(x=>`<li>${x.title}</li>`).join('');$('#seek').value=index;$('#progress').textContent=`${index+1} / ${events.length}`;$('#prev').disabled=index===0;$('#next').disabled=index===events.length-1;animate(t);}
function animate(t){const e=events[index],board=$('#board').getBoundingClientRect(),a=e.actor&&$('#seat-'+e.actor);$('#arrows').innerHTML='';$('#flying').style.display='none';if(!a)return;const p=a.getBoundingClientRect(),x=p.x+p.width/2-board.x,y=p.y+p.height/2-board.y;const q=Math.min(1,t/1.6);for(const id of e.targets){const target=$('#seat-'+id);if(!target)continue;const r=target.getBoundingClientRect(),tx=r.x+r.width/2-board.x,ty=r.y+r.height/2-board.y;$('#arrows').innerHTML+=`<path d="M ${x} ${y} Q ${board.width/2} ${board.height/2} ${tx} ${ty}" fill="none" stroke="#e4c47a" stroke-width="2.5" stroke-dasharray="7 7" opacity="${0.18+q*.45}"/>`;}
if(e.cards.length){const f=$('#flying');f.style.display='block';f.textContent=e.cards[0].split('|')[0];f.style.transform=`translate(${x+(board.width/2-x)*q-24}px,${y+(board.height/2-y)*q-20}px) scale(${.7+.3*q})`;f.style.opacity=t>2?0:1;}}
function go(n){elapsed=0;render(n);}
$('#play').onclick=()=>{if(index===events.length-1&&!playing)go(0);playing=!playing;$('#play').textContent=playing?'暂停':'继续播放';};$('#prev').onclick=()=>go(index-1);$('#next').onclick=()=>go(index+1);$('#speed').onchange=e=>rate=+e.target.value;$('#seek').max=events.length-1;$('#seek').oninput=e=>go(+e.target.value);$('#notes').onclick=()=>$('#notes-dialog').showModal();document.addEventListener('keydown',e=>{if(e.target.matches('input,select,button'))return;if(e.code==='Space'){e.preventDefault();$('#play').click();}if(e.code==='ArrowRight')go(index+1);if(e.code==='ArrowLeft')go(index-1);});
function tick(now){if(playing){elapsed+=(now-last)/1000*rate;if(elapsed>=events[index].duration){if(index<events.length-1)go(index+1);else{playing=false;$('#play').textContent='重新播放';}}animate(elapsed);}last=now;requestAnimationFrame(tick);}render(0);requestAnimationFrame(tick);
window.DEMO={events,ids,snapshot,render,setTime:(n,t)=>{playing=false;render(n,t);},coverage:()=>[...new Set(events.flatMap(e=>e.skills))]};
window.addEventListener('resize',()=>animate(elapsed));
if(new URLSearchParams(location.search).has('record'))document.body.classList.add('recording');
